---
name:        Zabbix Docker Module
url:         https://github.com/monitoringartist/Zabbix-Docker-Monitoring
shortinfo:   Compilation and installation of Docker module
fullinfo:    Zabbix C module for Docker monitoring      
maintainer:  Jan Garaj - www.monitoringartist.com
date:        2015-09-13
zversion:    2.4+
preactions:
    apt: apt-get install -y wget autoconf automake gcc subversion make pkg-config
    yum:     yum install -y wget autoconf automake gcc svn
actions:
    cd /tmp
    mkdir zabbix24
    cd zabbix24
    svn co svn://svn.zabbix.com/branches/2.4 .
    ./bootstrap.sh
    ./configure --enable-agent
    mkdir src/modules/zabbix_module_docker
    cd src/modules/zabbix_module_docker
    wget https://raw.githubusercontent.com/monitoringartist/Zabbix-Docker-Monitoring/master/src/modules/zabbix_module_docker/zabbix_module_docker.c
    wget https://raw.githubusercontent.com/monitoringartist/Zabbix-Docker-Monitoring/master/src/modules/zabbix_module_docker/Makefile
    make     
postactions:
    apt: apt-get autoremove -y wget autoconf automake gcc subversion make pkg-config
    yum:     yum autoremove -y wget autoconf automake gcc svn
           